plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'de.KnollFrank.routeoptimizerforgooglemaps'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    androidResources {
        generateLocaleConfig true
    }

    defaultConfig {
        applicationId "de.KnollFrank.routeoptimizerforgooglemaps"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "boolean", "FEATURE_ROUTE_PREVIEW_VISIBLE", "true"
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material

    // Core App Dependencies
    implementation libs.recyclerview
    implementation libs.jsprit.core
    implementation libs.okhttp
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.gson
    implementation libs.guava

    // ML Kit & CameraX
    implementation libs.mlkit.text.recognition
    implementation libs.camera.camera2
    implementation libs.camera.lifecycle
    implementation libs.camera.view

    testImplementation libs.junit
    testImplementation libs.mockwebserver
    testImplementation libs.robolectric
    testImplementation libs.mockito.core
    testImplementation libs.core

    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.uiautomator
    androidTestImplementation libs.rules
}